name: IMS SCAN CI

on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        php-version: [ '8.0', '8.1', '8.2' ]

    name: PHP ${{ matrix.php-version }}

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: azuriom
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: üõéÔ∏è Checkout repository
        uses: actions/checkout@v3

      - name: ‚öôÔ∏è Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo, sqlite, pdo_sqlite, bcmath, mbstring, curl, libxml, zip, intl, gd
          tools: composer

      - name: ü§ñ Install dependencies
        run: composer install --ansi --no-interaction --no-progress --prefer-dist

      - name: üîí SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        run: vendor/bin/phpunit
        env:
          APP_KEY: "base64:dpPUwuuA5ojUpdVwUJcPT13NdOe+RSM/1QXSW/VuJIc="
          DB_CONNECTION: mysql
          DB_DATABASE: azuriom
          DB_USERNAME: root
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }


  assets:
    name: Bundle assets

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run production
